apiVersion: v1
kind: Pod 
metadata:
  name: frontend-pod
  labels:
    app: frontend-app
spec:
containers:
  - name:  backend-app
    image: 
  - containerPort: 80

---
 
apiVersion: v1 
kind: Service
metadata: 
  name: frontend-svc
spec:
  ports: 
  - port: 80
    targetPort: 80
    name: http
    protocol: TCP
  selector:
    app: frontend-app
  type: LoadBalancer
