apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  labels:
    app: "easy-crud-db"
spec:
  containers:
  - name: mysql-container
    image: mariadb:latest
    ports:
     - containerPort: 3360
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: redhat
    - name: MYSQL_DATABASE
      value: student_db

---

apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app:  "easy-crud-db"
  ports:
  - name: mysql
    port:  3306
    targetPort: 3306
