apiVersion: v1 
kind: PersistentVolume
metadata: 
  name:  student-app-pv
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-05c9f23a447c3889c        # volume_ID
    fsType: ext4
    volumeAttributes:
      storage.kubernates.io/csiProvisionerIdentity: static
  nodeAffinity:
    required:
      nodeSelectorTerms:
       - matchExpressions:
         - {key: topology.kubernetes.io/zone, operator: In, values: ["us-east-1d"]} # kubectl get node --show-labels
   # ip-172-31-35-13
      #erator: In, values: ["- ip-172-31-35-13"] }
      
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: student-app-pvc
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem