apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: student-db-sts
  labels:
    app: student-app-db
spec:
  selector:
    matchLabels:
      app: student-app-db # has to match .spec.template.metadata.labels
  serviceName: student-app-db-svc
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        app: student-app-db # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: student-app-container
        image: mariadb:latest
        env:
          - name:  MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name:  my-secret
                key:  DB_PASS

          - name:  MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name:  my-secret
                key:  DB_NAME
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: student-db-volume
          mountPath: /var/lib/mysql
      volumes:
        - name: student-db-volume
          PersistentVolumeClaim: student-app-pvc